package entities;

public enum PlayerState {
	IDLE, RUNNING, AIRBORN, SHIELDING, STUNNED, ROLLING, SPOT_DODGING, AIR_DODGING, HANGING,
	
	//attacks
	ATTACKING, AIR_ATTACKING, GRABBING, BEING_GRABBED, AIR_HIT, KNOCKED_DOWN
}
